author: "Jay Wiggins"
title: "Jay, trying to remember..."
description: "code, music, food, fun and whatnot... (mostly code)"
more: "read more&hellip;"
email: blog@irk.com
url: "https://jaywiggins.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: funkfinger
github_username: funkfinger

google_analytics: UA-148448725-1

theme: minima

# existing minima format:
twitter_username: funkfinger
github_username:  funkfinger
instagram_username: funkfinger
pinterest_username: funkfinger
rss: rss

header_pages:
  - about.md
  - archive.html

# future minima format:
minima:
  social_links:
    twitter: funkfinger
    github: funkfinger
    flickr: funkfinger
    instagram: funkfinger
    pinterest: funkfinger
    rss: rss


baseurl: ""
paginate: 10
permalink: pretty
excerpt_separator: "\n\n" # two blank lines

show_excerpts: true

disqus:
  shortname: jaywiggins

defaults:
  [
    { scope: { path: "" }, values: { layout: "default" } },
    { scope: { path: "", type: "posts" }, values: { comments: true } },
  ]
sass: { style: expanded }
plugins:
  - jekyll-feed
  - jekyll-paginate
