author: "Jay Wiggins"
title: "Jay, trying to remember..."
description: "code, music, food, fun and whatnot... (mostly code)"
more: "read more&hellip;"
email: blog@irk.com
url: "https://jaywiggins.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: funkfinger
github_username: funkfinger

theme: minima

baseurl: ""
paginate: 10
permalink: pretty
excerpt_separator: "\n\n" # two blank lines

show_excerpts: true

disqus:
  shortname: jaywiggins

# comments:
# disqus: jaywiggins
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  # - twitter: "https://twitter.com/funkfinger/"
  - github: "https://github.com/funkfinger/wigg.in"
  - envelope: "mailto:blog@irk.com"

defaults:
  [
    { scope: { path: "" }, values: { layout: "default" } },
    { scope: { path: "", type: "posts" }, values: { comments: true } },
  ]
sass: { style: expanded }
plugins:
  - jekyll-feed
  - jekyll-paginate
